#import "basecolours.typ": *
#let palette = (
  red: (
    fg: tailwind.red-900,
    m2: tailwind.red-500,
    m1: tailwind.red-300,
    bbg: tailwind.red-50.mix(white).mix(white),
    bg: white,
  ),
  scarlet: (
    fg: tailwind.red-900.mix(tailwind.orange-900),
    m2: tailwind.red-500.mix(tailwind.orange-500),
    m1: tailwind.red-300.mix(tailwind.orange-300),
    bbg: tailwind.red-50.mix(tailwind.orange-50).mix(white).mix(white),
    bg: white,
  ),
  orange: (
    fg: tailwind.orange-900,
    m2: tailwind.orange-500,
    m1: tailwind.orange-300,
    bbg: tailwind.orange-50.mix(white).mix(white),
    bg: white,
  ),
  amber: (
    fg: tailwind.amber-900,
    m2: tailwind.amber-500,
    m1: tailwind.amber-300,
    bbg: tailwind.amber-50.mix(white).mix(white),
    bg: white,
  ),
  yellow: (
    fg: tailwind.yellow-900,
    m2: tailwind.yellow-500,
    m1: tailwind.yellow-300,
    bbg: tailwind.yellow-50.mix(white).mix(white),
    bg: white,
  ),
  pear: (
    fg: tailwind.yellow-900.mix(tailwind.lime-900),
    m2: tailwind.yellow-500.mix(tailwind.lime-500),
    m1: tailwind.yellow-300.mix(tailwind.lime-300),
    bbg: tailwind.yellow-50.mix(tailwind.lime-50).mix(white).mix(white),
    bg: white,
  ),
  lime: (
    fg: tailwind.lime-900,
    m2: tailwind.lime-500,
    m1: tailwind.lime-300,
    bbg: tailwind.lime-50.mix(white).mix(white),
    bg: white,
  ),
  midgreen: (
    fg: tailwind.green-900.mix(tailwind.lime-900),
    m2: tailwind.green-500.mix(tailwind.lime-500),
    m1: tailwind.green-300.mix(tailwind.lime-300),
    bbg: tailwind.green-50.mix(tailwind.lime-50).mix(white).mix(white),
    bg: white,
  ),
  green: (
    fg: tailwind.green-900,
    m2: tailwind.green-500,
    m1: tailwind.green-300,
    bbg: tailwind.green-50.mix(white).mix(white),
    bg: white,
  ),
  emerald: (
    fg: tailwind.emerald-900,
    m2: tailwind.emerald-500,
    m1: tailwind.emerald-300,
    bbg: tailwind.emerald-50.mix(white).mix(white),
    bg: white,
  ),
  teal: (
    fg: tailwind.teal-900,
    m2: tailwind.teal-500,
    m1: tailwind.teal-300,
    bbg: tailwind.teal-50.mix(white).mix(white),
    bg: white,
  ),
  jade: (
    fg: tailwind.teal-900.mix(tailwind.cyan-900),
    m2: tailwind.teal-500.mix(tailwind.cyan-500),
    m1: tailwind.teal-300.mix(tailwind.cyan-300),
    bbg: tailwind.teal-50.mix(tailwind.cyan-50).mix(white).mix(white),
    bg: white,
  ),
  cyan: (
    fg: tailwind.cyan-900,
    m2: tailwind.cyan-500,
    m1: tailwind.cyan-300,
    bbg: tailwind.cyan-50.mix(white).mix(white),
    bg: white,
  ),
  cerulean: (
    fg: tailwind.sky-900.mix(tailwind.cyan-900),
    m2: tailwind.sky-500.mix(tailwind.cyan-500),
    m1: tailwind.sky-300.mix(tailwind.cyan-300),
    bbg: tailwind.sky-50.mix(tailwind.cyan-50).mix(white).mix(white),
    bg: white,
  ),
  sky: (
    fg: tailwind.sky-900,
    m2: tailwind.sky-500,
    m1: tailwind.sky-300,
    bbg: tailwind.sky-50.mix(white).mix(white),
    bg: white,
  ),
  azure: (
    fg: tailwind.sky-900.mix(tailwind.blue-900),
    m2: tailwind.sky-500.mix(tailwind.blue-500),
    m1: tailwind.sky-300.mix(tailwind.blue-300),
    bbg: tailwind.sky-50.mix(tailwind.blue-50).mix(white).mix(white),
    bg: white,
  ),
  blue: (
    fg: tailwind.blue-900,
    m2: tailwind.blue-500,
    m1: tailwind.blue-300,
    bbg: tailwind.blue-50.mix(white).mix(white),
    bg: white,
  ),
  indigo: (
    fg: tailwind.indigo-900,
    m2: tailwind.indigo-500,
    m1: tailwind.indigo-300,
    bbg: tailwind.indigo-50.mix(white).mix(white),
    bg: white,
  ),
  violet: (
    fg: tailwind.violet-900,
    m2: tailwind.violet-500,
    m1: tailwind.violet-300,
    bbg: tailwind.violet-50.mix(white).mix(white),
    bg: white,
  ),
  purple: (
    fg: tailwind.purple-900,
    m2: tailwind.purple-500,
    m1: tailwind.purple-300,
    bbg: tailwind.purple-50.mix(white).mix(white),
    bg: white,
  ),
  midpurple: (
    fg: tailwind.purple-900.mix(tailwind.fuchsia-900),
    m2: tailwind.purple-500.mix(tailwind.fuchsia-500),
    m1: tailwind.purple-300.mix(tailwind.fuchsia-300),
    bbg: tailwind.purple-50.mix(tailwind.fuchsia-50).mix(white).mix(white),
    bg: white,
  ),
  fuchsia: (
    fg: tailwind.fuchsia-900,
    m2: tailwind.fuchsia-500,
    m1: tailwind.fuchsia-300,
    bbg: tailwind.fuchsia-50.mix(white).mix(white),
    bg: white,
  ),
  magenta: (
    fg: tailwind.fuchsia-900.mix(tailwind.pink-900),
    m2: tailwind.fuchsia-500.mix(tailwind.pink-500),
    m1: tailwind.fuchsia-300.mix(tailwind.pink-300),
    bbg: tailwind.fuchsia-50.mix(tailwind.pink-50).mix(white).mix(white),
    bg: white,
  ),
  pink: (
    fg: tailwind.pink-900,
    m2: tailwind.pink-500,
    m1: tailwind.pink-300,
    bbg: tailwind.pink-50.mix(white).mix(white),
    bg: white,
    ),
  rose: (
    fg: tailwind.rose-900,
    m2: tailwind.rose-500,
    m1: tailwind.rose-300,
    bbg: tailwind.rose-50.mix(white).mix(white),
    bg: white,
    ),
  rosegold: (
    fg: tailwind.rose-900.mix(tailwind.stone-900),
    m2: tailwind.rose-500.mix(tailwind.stone-500),
    m1: tailwind.rose-300.mix(tailwind.stone-300),
    bbg: tailwind.rose-50.mix(tailwind.stone-50).mix(white).mix(white),
    bg: white,
  ),
  brown: (
    fg: tailwind.orange-900.mix(tailwind.stone-900),
    m2: tailwind.orange-500.mix(tailwind.stone-500),
    m1: tailwind.orange-300.mix(tailwind.stone-300),
    bbg: tailwind.orange-50.mix(tailwind.stone-50).mix(white).mix(white),
    bg: white,
  ),
  gold: (
    fg: tailwind.yellow-900.mix(tailwind.stone-900),
    m2: tailwind.yellow-500.mix(tailwind.stone-500),
    m1: tailwind.yellow-300.mix(tailwind.stone-300),
    bbg: tailwind.yellow-50.mix(tailwind.stone-50).mix(white).mix(white),
    bg: white,
  ),
  pine: (
    fg: tailwind.emerald-900.mix(tailwind.stone-900),
    m2: tailwind.emerald-500.mix(tailwind.stone-500),
    m1: tailwind.emerald-300.mix(tailwind.stone-300),
    bbg: tailwind.emerald-50.mix(tailwind.stone-50).mix(white).mix(white),
    bg: white,
  ),
  bluegrey: (
    fg: tailwind.blue-900.mix(tailwind.stone-900),
    m2: tailwind.blue-500.mix(tailwind.stone-500),
    m1: tailwind.blue-300.mix(tailwind.stone-300),
    bbg: tailwind.blue-50.mix(tailwind.stone-50).mix(white).mix(white),
    bg: white,
  ),
  plum: (
    fg: tailwind.fuchsia-900.mix(tailwind.stone-900),
    m2: tailwind.fuchsia-500.mix(tailwind.stone-500),
    m1: tailwind.fuchsia-300.mix(tailwind.stone-300),
    bbg: tailwind.fuchsia-50.mix(tailwind.stone-50).mix(white).mix(white),
    bg: white,
  ),
  stone: (
    fg: tailwind.stone-900,
    m2: tailwind.stone-500,
    m1: tailwind.stone-300,
    bbg: tailwind.stone-50.mix(white).mix(white),
    bg: white,
  ),
  neutral: (
    fg: tailwind.neutral-900,
    m2: tailwind.neutral-500,
    m1: tailwind.neutral-300,
    bbg: tailwind.neutral-50.mix(white).mix(white),
    bg: white,
  ),
  zinc: (fg: tailwind.zinc-900, m2: tailwind.zinc-500, m1: tailwind.zinc-300, bbg: tailwind.zinc-50.mix(white).mix(white),
  bg: white,),
  grey: (fg: tailwind.gray-900, m2: tailwind.gray-500, m1: tailwind.gray-300, bbg: tailwind.gray-50.mix(white).mix(white),
  bg: white,),
  slate: (
    fg: tailwind.slate-900,
    m2: tailwind.slate-500,
    m1: tailwind.slate-300,
    bbg: tailwind.slate-50.mix(white).mix(white),
    bg: white,
  ),
  default: (
    fg: rdbp.romeo-fg,
    m2: rdbp.romeo-m2,
    m1: rdbp.romeo-m1,
    bg: rdbp.romeo-bg,
  ),
)

#set text(font: "Romeosevka", size: 10pt)
#set page(margin: 0.25in, width: 6.5in, height: 13in, columns: 2)
#for col in palette {
  block(breakable: false)[
    #raw(col.at(0)); #v(-0.9em)
    #for i in col.at(1).values() {
      box(rect(height: 30pt, width: 30pt * 6 / col.at(1).values().len(), stroke: 0pt + black, fill: i))
    }]
  v(-0.5em)
}
count: *#palette.len()*
